[package]
name = "minimal-sui-types"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bcs = "0.1"
anyhow = "1.0"
eyre = "0.6"
base64 = "0.21"
hex = "0.4"
